server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: 9090
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
